### ISSUE TITLE
Does it support name aliases?

### ISSUE THREAD

**Issue by non-descriptive** [pouriya/keshvar#17]
The example suggest that you can use any language to lookup for country. Does it support aliases?
```rust
let country_name_in_any_language = "estados unidos"; // The US in spanish!
```
I've seen inside code Russian alias for the US (which generally is USA) and seen only "Соединённые Штаты", which generally doesn't used and exists in forms "Соединённые Штаты Америки", "Штаты" (informal speech) and "США" (abbrev). Does it supports such aliasing?
Also there's "США" under `uk` key which i believe supposed to be Ukraine (their code is `ua`) but has tag of United Kindom. And probably should have long form as ["Сполучені Штати Америки"](https://uk.wikipedia.org/wiki/%D0%A1%D0%BF%D0%BE%D0%BB%D1%83%D1%87%D0%B5%D0%BD%D1%96_%D0%A8%D1%82%D0%B0%D1%82%D0%B8_%D0%90%D0%BC%D0%B5%D1%80%D0%B8%D0%BA%D0%B8)

**Comment by pouriya** [comment]
For every country there is a list `unofficial_name_list` that contains some popular names for that country.
For example for The US, [this is the list](https://github.com/pouriya/keshvar/blob/0.1.4/src/countries/us.rs#L40):  
```rust
pub const UNOFFICIAL_NAME_LIST: &[&str] = &[
        "United States",
        "USA",
        "Vereinigte Staaten von Amerika",
        "États-Unis",
        "Estados Unidos",
        "アメリカ合衆国",
        "Verenigde Staten",
        "Соединенные Штаты Америки",
    ];
```
By using [find_by_name](https://docs.rs/keshvar/0.1.4/keshvar/fn.find_by_name.html) function, `keshvar` tries to search these lists too.

**Comment by pouriya** [comment]
If you think some names are missing in some languages. I recommend to make a contribution to our submodule library. for more info see `CONTRIBUTING.md` file.

**Comment by non-descriptive** [comment]
What about `uk`/`ua`? Is it supposed to find things forward to english or other way around should also be working?

**Comment by pouriya** [comment]
Found [the commit](https://github.com/countries/countries-data-yaml/commit/5f723a0dabd0fdbe5bcc9997957573261d00512e#diff-f3dbfe014c0d046cbabbf0d51b0c61733b194eccef7b9f262727aaa7a5ea336d). Since I could not find a separate PR for just this change, I think you can make a new PR and improve it (if you believe something's wrong).
