### ISSUE TITLE
Country information is inaccurate and incomplete.

### ISSUE THREAD

**Issue by Cthutu** [pouriya/keshvar#19]
I am finding the information wrong about the countries I've tried.

Example: `find_by_name("england")` returns:

"The United Kingdom of Great Britain and Northern Ireland"

and a language list of just "en".  This is inaccurate (there is no Welsh language, Scots of Gaelic).  England and UK are not synoymous and the language list is incomplete.

Additionally, try "wales" and it is not found at all.  Why is "England" found and not "Wales"?  How can we contribute to fix these issues?  Or are you using a 3rd party database?

**Comment by pouriya** [comment]
>  How can we contribute to fix these issues?
See [CONTRIBUTING.md](https://github.com/pouriya/keshvar/blob/0.1.4/CONTRIBUTING.md)

> Are you using a 3rd party database?
Yes. [CONTRIBUTING.md](https://github.com/pouriya/keshvar/blob/0.1.4/CONTRIBUTING.md) contains information about 3rd-party repository too.
