### ISSUE TITLE
Expose `&str` with `'static` lifetimes where possible

### ISSUE THREAD

**Issue by MOZGIII** [pouriya/keshvar#27]
Using this crate is a relatively high-perf setting where doing a clone of a string to pass it around it kind of unwanted. It would be great if the crate would allow to just use static references for things that allow it.

For instance: `country.un_locale()` could easily return `&'static str` instead of `&str`.

**Comment by pouriya** [comment]
Hmm. yeah. I think we need to change [this](https://github.com/pouriya/keshvar/blob/master/src/country.rs#L70-L231) section. Could you do that?

**Comment by MOZGIII** [comment]
I use only a small part of the API surface - so I don't really know where to look for all the instances where this would be relevant. So, I'd avoid taking this task.

**Comment by MOZGIII** [comment]
I mean, I suspect there are also other placrs where this would matter, besides the file you linked

**Comment by pouriya** [comment]
[Done](https://github.com/pouriya/keshvar/pull/32)
