### ISSUE TITLE
feature request: adding current population as a field

### ISSUE THREAD

**Issue by rbozan** [pouriya/keshvar#28]
Thanks for the awesome crate.

My suggestion would be to add population as a field to a country / subdivision. Is this something the author of the crate would be interested in, or would that be out of scope for this project? Most information in this crate is not changing that often, whilst population changes more frequently.

**Comment by pouriya** [comment]
Hi. I'm glad you liked it. Is there a way (repo, API, etc.) to get **updated** population data for every country?

**Comment by rbozan** [comment]
I'm not completely sure, but I did stumble upon these 2 repos which could be interesting:

https://github.com/MartinsOnuoha/countriesNowAPI (seems to use data from https://datahub.io/)
https://github.com/datasets/population (uses the data from WorldBank)

The WorldBank dataset seems to have data from 2022 with the CC BY-4.0 license.

There's also this dataset being used by several sites (like https://www.worldometers.info/world-population/population-by-country/):
https://population.un.org/wpp/Download/Standard/MostUsed/

**Comment by pouriya** [comment]
[Done](https://github.com/pouriya/keshvar/pull/31)

**Comment by rbozan** [comment]
That is so awesome, thank you so much
